version: '3.5'

services:
  db_wallet:
    container_name: db_wallet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - TZ=Europe/Moscow
    image: postgres:14.3-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - wallet_network

networks:
  wallet_network:
    driver: bridge
